#!/usr/bin/env ruby
# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#++

require "ebook_library_manager"

warn "elm: not yet implemented (scaffold placeholder)"
exit 1
